classDiagram
    direction TB

    %% Game
    class Game {
        +Board : Board
        +RecruitableCards : List~CharacterCard~
        +RecruitedCharacters : List~Character~
        +BanishedCards : List~CharacterCard~
    }

    %% Handlers
    class IActionHandler {
        <<interface>>
        +Game : Game
        +History : GameHistory
        +DoAction()
        +UndoAction()
    }
    class TransitionActionHandler
    class RecruitmentActionHandler
    class BanishmentActionHandler
    class CharacterActionHandler

    %% Resolvers
    class CharacterActionResolver {
        <<abstract>>
        +GetMovementActions() List~CharacterAction~
        +GetActiveAbilityActions() List~CharacterAction~
    }

    class RecruitmentActionResolver {
        +GetRecruitmentActions(CharacterCard) List~RecruitmentAction~
    }

    %% Queries
    class BoardQuery {
        <<static>>
        +GetCell() Cell
        +FindAdjacentCell() Cell
        +FindLeaderCell() Cell
        +GetCharacterCellById() Cell
        +FindCellsWithMatchingCharacter() Cell
    }

    class GameQuery {
        <<static>>
        +IsLeaderCaptured() Boolean
        +IsLeaderSurrounded() Boolean
        +IsBarrageDetected() Boolean
    }

    class PlayabilityQuery {
        <<static>>
        +CanAct(Character, Game, GameHistory) Boolean
        +MustAct(Character, Game, GameHistory) Boolean
        +CanUseActiveAbility(Character, Game, GameHistory) Boolean
        +GetPlayableCharacters(Game, GameHistory) List~Cell~
    }

    %% Factories
    class BoardFactory {
        <<static>>
        +Create() Board
    }
    class GameFactory {
        <<static>>
        +Create(GameConfig, GameHistory) Game
    }
    class CharacterFactory {
        <<static>>
        +Create() Character
        +Transform(Character, CharacterType, TeamColor) Character
    }
    class GameActionHandlerFactory {
        <<static>>
        +Create(gameAction : IGameAction) IActionHandler
    }
    class CharacterActionResolverFactory {
        <<static>>
        +Create(type : CharacterType) CharacterActionResolver
    }

    %% GameHandler
    class GameHandler {
        +CurrentGame : Game
        +CurrentHistory : GameHistory
        +GetGameMode() GameMode
        +GetPlayers Player[]
        +GetCurrentPlayer() Player
        +GetPlayableCharacters() List~Cell~
        +GetMovementActions(Character) List~CharacterAction~
        +GetActiveAbilityActions(Character) List~CharacterAction~
        +GetRecruitmentActions(Character) List~RecruitmentAction~
        +GetBanishmentAction(Character) BanishmentAction
        +DoAction(IGameAction)
        +UndoLastAction()
        +GetWinner() Player
    }

    %% Héritage handlers
    IActionHandler <|.. TransitionActionHandler
    IActionHandler <|.. RecruitmentActionHandler
    IActionHandler <|.. BanishmentActionHandler
    IActionHandler <|.. CharacterActionHandler

    %% GameFactory
    GameFactory ..> BoardFactory
    GameFactory ..> CharacterFactory
    GameFactory ..> GameActionHandlerFactory
    GameFactory ..> Game

    %% GameHandler
    GameHandler --> Game
    GameHandler --> GameHistory
    GameHandler --> GameActionHandlerFactory
    GameHandler --> CharacterActionResolverFactory
    GameHandler ..> CharacterActionResolver
    GameHandler ..> RecruitmentActionResolver
    GameHandler ..> IActionHandler
    GameHandler --> GameQuery
    GameHandler --> PlayabilityQuery

    %% Resolvers
    CharacterActionResolver ..> BoardQuery
    CharacterActionResolver ..> GameQuery
    RecruitmentActionResolver ..> BoardQuery
    CharacterActionResolverFactory ..> CharacterActionResolver

    %% Queries
    GameQuery ..> Game
    PlayabilityQuery ..> Game
    PlayabilityQuery ..> GameHistory
