classDiagram
    direction TB

    %% Enums
    class CharacterType {
        <<enumeration>>
    }

    %% Game
    class Game {
        +Players : List~Player~
        +FirstPlayer : Player
        +CurrentPlayer : Player
        +CurrentPhase : TurnPhase
        +Board : Board
        +GameMode : GameMode
        +RecruitableCards : List~CharacterCard~
        CharacterStates : Dictionary~Character, CharacterState~
        +History : List~IGameAction~
    }

    %% Handlers
    class IActionHandler {
        <<interface>>
        +DoAction()
        +UndoAction()
    }
    class PhaseChangeActionHandler
    class RecruitmentActionHandler
    class BanishmentActionHandler
    class CharacterActionHandler {
        <<abstract>>
    }

    %% Resolvers
    class CharacterActionResolver {
        <<abstract>>
        +GetMovementActions()
        +GetActiveAbilityActions()
    }

    %% Query
    class BoardQuery {
        <<static>>
        +GetCell() Cell
        +FindAdjacentCell() Cell
        +FindLeaderCell() Cell
        +GetCharacterCellById() Cell
        +FindCellsWithMatchingCharacter() Cell
    }

    class GameQuery {
        <<static>>
        +IsLeaderCaptured() Boolean
        +IsLeaderSurrounded() Boolean
        +IsBarrageDetected() Boolean
    }

    %% Factories
    class BoardFactory {
        <<static>>
        +Create()
    }
    class GameFactory {
        <<static>>
        +Create() Game
    }
    class CharacterFactory {
        <<static>>
        +Create()
    }
    class CharacterActionFactory {
        <<static>>
        +CreateMovement()
        +CreateAbilityActivation()
    }
    class CharacterActionResolverFactory {
        <<static>>
        +Create(type : CharacterType) CharacterActionResolver
    }
    class CharacterActionHandlerFactory {
        <<static>>
        +Create(type : CharacterType) CharacterActionHandler
    }

    %% GameHandler
    class GameHandler {
        +CurrentGame : Game
        +GetPlayableCharacters() List~CharacterContext~
        +GetMovementActions() List~CharacterAction~
        +GetActiveAbilityActions() List~CharacterAction~
        +GetRecruitmentActions() List~RecruitmentAction~
        +GetBanishmentActions() List~BanishmentAction~
        +DoAction()
        +UndoLastAction()
        +IsGameOver() Boolean
    }

    %% Héritage handlers
    IActionHandler <|.. PhaseChangeActionHandler
    IActionHandler <|.. RecruitmentActionHandler
    IActionHandler <|.. BanishmentActionHandler
    IActionHandler <|.. CharacterActionHandler

    %% GameFactory produit Game
    GameFactory ..> BoardFactory
    GameFactory ..> CharacterFactory
    GameFactory ..> Game

    %% GameHandler
    GameHandler --> Game
    GameHandler --> CharacterActionResolverFactory
    GameHandler --> CharacterActionHandlerFactory
    GameHandler ..> CharacterActionResolver
    GameHandler ..> IActionHandler
    GameHandler --> GameQuery

    %% Resolver
    CharacterActionResolver ..> BoardQuery
    CharacterActionResolver ..> GameQuery
    CharacterActionResolver ..> CharacterActionFactory
    CharacterActionResolverFactory ..> CharacterActionResolver
    CharacterActionResolverFactory --> CharacterType
    CharacterActionHandlerFactory ..> CharacterActionHandler
    CharacterActionHandlerFactory --> CharacterType

    %% GameQuery
    GameQuery ..> Game